[package]
name = "lexical-lifetime"
version = "1.0.0"
edition = "2018"
repository = "https://github.com/That3Percent/lexical-lifetime"
license = "MIT"
description = "Extend lifetimes to the end of the lexical scope"